// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/blue.dart';
import 'api/log.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'package:meta/meta.dart' as meta;
import 'package:uuid/uuid.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_BPeripheralPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheralPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_BlueAdapterPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapterPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  BPeripheral
      dco_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
          dynamic raw);

  @protected
  BPeripheral
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
          dynamic raw);

  @protected
  BlueAdapter
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
          dynamic raw);

  @protected
  BPeripheral
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
          dynamic raw);

  @protected
  BlueAdapter
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
          dynamic raw);

  @protected
  Map<UuidValue, Uint8List> dco_decode_Map_Uuid_list_prim_u_8_strict_None(
      dynamic raw);

  @protected
  Map<int, Uint8List> dco_decode_Map_u_16_list_prim_u_8_strict_None(
      dynamic raw);

  @protected
  BPeripheral
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
          dynamic raw);

  @protected
  BlueAdapter
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
          dynamic raw);

  @protected
  RustStreamSink<BlueEvent> dco_decode_StreamSink_blue_event_Dco(dynamic raw);

  @protected
  RustStreamSink<LogEntry> dco_decode_StreamSink_log_entry_Dco(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  UuidValue dco_decode_Uuid(dynamic raw);

  @protected
  BCentralState dco_decode_b_central_state(dynamic raw);

  @protected
  BCharacteristic dco_decode_b_characteristic(dynamic raw);

  @protected
  BWriteType dco_decode_b_write_type(dynamic raw);

  @protected
  BlueEvent dco_decode_blue_event(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BCharacteristic dco_decode_box_autoadd_b_characteristic(dynamic raw);

  @protected
  DevicePeripheralId dco_decode_box_autoadd_device_peripheral_id(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_16(dynamic raw);

  @protected
  DevicePeripheralId dco_decode_device_peripheral_id(dynamic raw);

  @protected
  int dco_decode_i_16(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<BlueAdapter>
      dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
          dynamic raw);

  @protected
  List<UuidValue> dco_decode_list_Uuid(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(int, Uint8List)> dco_decode_list_record_u_16_list_prim_u_8_strict(
      dynamic raw);

  @protected
  List<(UuidValue, Uint8List)> dco_decode_list_record_uuid_list_prim_u_8_strict(
      dynamic raw);

  @protected
  LogEntry dco_decode_log_entry(dynamic raw);

  @protected
  MyMobileLogger dco_decode_my_mobile_logger(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_16(dynamic raw);

  @protected
  (int, Uint8List) dco_decode_record_u_16_list_prim_u_8_strict(dynamic raw);

  @protected
  (UuidValue, Uint8List) dco_decode_record_uuid_list_prim_u_8_strict(
      dynamic raw);

  @protected
  SendToDartLogger dco_decode_send_to_dart_logger(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  BPeripheral
      sse_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
          SseDeserializer deserializer);

  @protected
  BPeripheral
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
          SseDeserializer deserializer);

  @protected
  BlueAdapter
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
          SseDeserializer deserializer);

  @protected
  BPeripheral
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
          SseDeserializer deserializer);

  @protected
  BlueAdapter
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
          SseDeserializer deserializer);

  @protected
  Map<UuidValue, Uint8List> sse_decode_Map_Uuid_list_prim_u_8_strict_None(
      SseDeserializer deserializer);

  @protected
  Map<int, Uint8List> sse_decode_Map_u_16_list_prim_u_8_strict_None(
      SseDeserializer deserializer);

  @protected
  BPeripheral
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
          SseDeserializer deserializer);

  @protected
  BlueAdapter
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<BlueEvent> sse_decode_StreamSink_blue_event_Dco(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<LogEntry> sse_decode_StreamSink_log_entry_Dco(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  UuidValue sse_decode_Uuid(SseDeserializer deserializer);

  @protected
  BCentralState sse_decode_b_central_state(SseDeserializer deserializer);

  @protected
  BCharacteristic sse_decode_b_characteristic(SseDeserializer deserializer);

  @protected
  BWriteType sse_decode_b_write_type(SseDeserializer deserializer);

  @protected
  BlueEvent sse_decode_blue_event(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BCharacteristic sse_decode_box_autoadd_b_characteristic(
      SseDeserializer deserializer);

  @protected
  DevicePeripheralId sse_decode_box_autoadd_device_peripheral_id(
      SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_16(SseDeserializer deserializer);

  @protected
  DevicePeripheralId sse_decode_device_peripheral_id(
      SseDeserializer deserializer);

  @protected
  int sse_decode_i_16(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<BlueAdapter>
      sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
          SseDeserializer deserializer);

  @protected
  List<UuidValue> sse_decode_list_Uuid(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(int, Uint8List)> sse_decode_list_record_u_16_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  List<(UuidValue, Uint8List)> sse_decode_list_record_uuid_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  LogEntry sse_decode_log_entry(SseDeserializer deserializer);

  @protected
  MyMobileLogger sse_decode_my_mobile_logger(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_16(SseDeserializer deserializer);

  @protected
  (int, Uint8List) sse_decode_record_u_16_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  (UuidValue, Uint8List) sse_decode_record_uuid_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  SendToDartLogger sse_decode_send_to_dart_logger(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_AnyhowException(
      AnyhowException raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  int cst_encode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
      BPeripheral raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
        raw);
  }

  @protected
  ffi.Pointer<wire_cst_list_record_uuid_list_prim_u_8_strict>
      cst_encode_Map_Uuid_list_prim_u_8_strict_None(
          Map<UuidValue, Uint8List> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_record_uuid_list_prim_u_8_strict(
        raw.entries.map((e) => (e.key, e.value)).toList());
  }

  @protected
  ffi.Pointer<wire_cst_list_record_u_16_list_prim_u_8_strict>
      cst_encode_Map_u_16_list_prim_u_8_strict_None(Map<int, Uint8List> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_record_u_16_list_prim_u_8_strict(
        raw.entries.map((e) => (e.key, e.value)).toList());
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict>
      cst_encode_StreamSink_blue_event_Dco(RustStreamSink<BlueEvent> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(raw.setupAndSerialize(
        codec: DcoCodec(
      decodeSuccessData: dco_decode_blue_event,
      decodeErrorData: dco_decode_AnyhowException,
    )));
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict>
      cst_encode_StreamSink_log_entry_Dco(RustStreamSink<LogEntry> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(raw.setupAndSerialize(
        codec: DcoCodec(
      decodeSuccessData: dco_decode_log_entry,
      decodeErrorData: dco_decode_AnyhowException,
    )));
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_Uuid(UuidValue raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(raw.toBytes());
  }

  @protected
  ffi.Pointer<wire_cst_b_characteristic>
      cst_encode_box_autoadd_b_characteristic(BCharacteristic raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_b_characteristic();
    cst_api_fill_to_wire_b_characteristic(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_device_peripheral_id>
      cst_encode_box_autoadd_device_peripheral_id(DevicePeripheralId raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_device_peripheral_id();
    cst_api_fill_to_wire_device_peripheral_id(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<ffi.Int16> cst_encode_box_autoadd_i_16(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_i_16(cst_encode_i_16(raw));
  }

  @protected
  int cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toInt();
  }

  @protected
  ffi.Pointer<
          wire_cst_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter>
      cst_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
          List<BlueAdapter> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire
        .cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
            raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] =
          cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
              raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_Uuid> cst_encode_list_Uuid(List<UuidValue> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_Uuid(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_Uuid(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_encode_list_prim_u_8_loose(
      List<int> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
      Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_record_u_16_list_prim_u_8_strict>
      cst_encode_list_record_u_16_list_prim_u_8_strict(
          List<(int, Uint8List)> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_record_u_16_list_prim_u_8_strict(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_record_u_16_list_prim_u_8_strict(
          raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_record_uuid_list_prim_u_8_strict>
      cst_encode_list_record_uuid_list_prim_u_8_strict(
          List<(UuidValue, Uint8List)> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_record_uuid_list_prim_u_8_strict(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_record_uuid_list_prim_u_8_strict(
          raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
      String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<ffi.Int16> cst_encode_opt_box_autoadd_i_16(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_i_16(raw);
  }

  @protected
  int cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_b_characteristic(
      BCharacteristic apiObj, wire_cst_b_characteristic wireObj) {
    wireObj.uuid = cst_encode_Uuid(apiObj.uuid);
    wireObj.service_uuid = cst_encode_Uuid(apiObj.serviceUuid);
  }

  @protected
  void cst_api_fill_to_wire_blue_event(
      BlueEvent apiObj, wire_cst_blue_event wireObj) {
    if (apiObj is BlueEvent_DeviceDiscovered) {
      var pre_field0 =
          cst_encode_box_autoadd_device_peripheral_id(apiObj.field0);
      wireObj.tag = 0;
      wireObj.kind.DeviceDiscovered.field0 = pre_field0;
      return;
    }
    if (apiObj is BlueEvent_DeviceUpdated) {
      var pre_field0 =
          cst_encode_box_autoadd_device_peripheral_id(apiObj.field0);
      wireObj.tag = 1;
      wireObj.kind.DeviceUpdated.field0 = pre_field0;
      return;
    }
    if (apiObj is BlueEvent_DeviceConnected) {
      var pre_field0 =
          cst_encode_box_autoadd_device_peripheral_id(apiObj.field0);
      wireObj.tag = 2;
      wireObj.kind.DeviceConnected.field0 = pre_field0;
      return;
    }
    if (apiObj is BlueEvent_DeviceDisconnected) {
      var pre_field0 =
          cst_encode_box_autoadd_device_peripheral_id(apiObj.field0);
      wireObj.tag = 3;
      wireObj.kind.DeviceDisconnected.field0 = pre_field0;
      return;
    }
    if (apiObj is BlueEvent_ManufacturerDataAdvertisement) {
      var pre_field0 =
          cst_encode_box_autoadd_device_peripheral_id(apiObj.field0);
      var pre_field1 =
          cst_encode_Map_u_16_list_prim_u_8_strict_None(apiObj.field1);
      wireObj.tag = 4;
      wireObj.kind.ManufacturerDataAdvertisement.field0 = pre_field0;
      wireObj.kind.ManufacturerDataAdvertisement.field1 = pre_field1;
      return;
    }
    if (apiObj is BlueEvent_ServiceDataAdvertisement) {
      var pre_field0 =
          cst_encode_box_autoadd_device_peripheral_id(apiObj.field0);
      var pre_field1 =
          cst_encode_Map_Uuid_list_prim_u_8_strict_None(apiObj.field1);
      wireObj.tag = 5;
      wireObj.kind.ServiceDataAdvertisement.field0 = pre_field0;
      wireObj.kind.ServiceDataAdvertisement.field1 = pre_field1;
      return;
    }
    if (apiObj is BlueEvent_ServicesAdvertisement) {
      var pre_field0 =
          cst_encode_box_autoadd_device_peripheral_id(apiObj.field0);
      var pre_field1 = cst_encode_list_Uuid(apiObj.field1);
      wireObj.tag = 6;
      wireObj.kind.ServicesAdvertisement.field0 = pre_field0;
      wireObj.kind.ServicesAdvertisement.field1 = pre_field1;
      return;
    }
    if (apiObj is BlueEvent_StateUpdate) {
      var pre_field0 = cst_encode_b_central_state(apiObj.field0);
      wireObj.tag = 7;
      wireObj.kind.StateUpdate.field0 = pre_field0;
      return;
    }
    if (apiObj is BlueEvent_ERROR) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 8;
      wireObj.kind.ERROR.field0 = pre_field0;
      return;
    }
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_b_characteristic(
      BCharacteristic apiObj, ffi.Pointer<wire_cst_b_characteristic> wireObj) {
    cst_api_fill_to_wire_b_characteristic(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_device_peripheral_id(
      DevicePeripheralId apiObj,
      ffi.Pointer<wire_cst_device_peripheral_id> wireObj) {
    cst_api_fill_to_wire_device_peripheral_id(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_device_peripheral_id(
      DevicePeripheralId apiObj, wire_cst_device_peripheral_id wireObj) {
    wireObj.name = cst_encode_opt_String(apiObj.name);
    wireObj.is_connected = cst_encode_bool(apiObj.isConnected);
    wireObj.address = cst_encode_String(apiObj.address);
    wireObj.tx_power_level =
        cst_encode_opt_box_autoadd_i_16(apiObj.txPowerLevel);
    wireObj.rssi = cst_encode_opt_box_autoadd_i_16(apiObj.rssi);
    wireObj.manufacturer_data =
        cst_encode_Map_u_16_list_prim_u_8_strict_None(apiObj.manufacturerData);
    wireObj.service_data =
        cst_encode_Map_Uuid_list_prim_u_8_strict_None(apiObj.serviceData);
    wireObj.services = cst_encode_list_Uuid(apiObj.services);
    wireObj.peripheral =
        cst_encode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
            apiObj.peripheral);
  }

  @protected
  void cst_api_fill_to_wire_log_entry(
      LogEntry apiObj, wire_cst_log_entry wireObj) {
    wireObj.time_millis = cst_encode_i_64(apiObj.timeMillis);
    wireObj.level = cst_encode_i_32(apiObj.level);
    wireObj.tag = cst_encode_String(apiObj.tag);
    wireObj.msg = cst_encode_String(apiObj.msg);
  }

  @protected
  void cst_api_fill_to_wire_my_mobile_logger(
      MyMobileLogger apiObj, wire_cst_my_mobile_logger wireObj) {}

  @protected
  void cst_api_fill_to_wire_record_u_16_list_prim_u_8_strict(
      (int, Uint8List) apiObj,
      wire_cst_record_u_16_list_prim_u_8_strict wireObj) {
    wireObj.field0 = cst_encode_u_16(apiObj.$1);
    wireObj.field1 = cst_encode_list_prim_u_8_strict(apiObj.$2);
  }

  @protected
  void cst_api_fill_to_wire_record_uuid_list_prim_u_8_strict(
      (UuidValue, Uint8List) apiObj,
      wire_cst_record_uuid_list_prim_u_8_strict wireObj) {
    wireObj.field0 = cst_encode_Uuid(apiObj.$1);
    wireObj.field1 = cst_encode_list_prim_u_8_strict(apiObj.$2);
  }

  @protected
  void cst_api_fill_to_wire_send_to_dart_logger(
      SendToDartLogger apiObj, wire_cst_send_to_dart_logger wireObj) {}

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
      BPeripheral raw);

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
      BlueAdapter raw);

  @protected
  int cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
      BPeripheral raw);

  @protected
  int cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
      BlueAdapter raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
      BPeripheral raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
      BlueAdapter raw);

  @protected
  int cst_encode_b_central_state(BCentralState raw);

  @protected
  int cst_encode_b_write_type(BWriteType raw);

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_i_16(int raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_u_16(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
          BPeripheral self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
          BPeripheral self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
          BlueAdapter self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
          BPeripheral self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
          BlueAdapter self, SseSerializer serializer);

  @protected
  void sse_encode_Map_Uuid_list_prim_u_8_strict_None(
      Map<UuidValue, Uint8List> self, SseSerializer serializer);

  @protected
  void sse_encode_Map_u_16_list_prim_u_8_strict_None(
      Map<int, Uint8List> self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
          BPeripheral self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
          BlueAdapter self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_blue_event_Dco(
      RustStreamSink<BlueEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_log_entry_Dco(
      RustStreamSink<LogEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_Uuid(UuidValue self, SseSerializer serializer);

  @protected
  void sse_encode_b_central_state(BCentralState self, SseSerializer serializer);

  @protected
  void sse_encode_b_characteristic(
      BCharacteristic self, SseSerializer serializer);

  @protected
  void sse_encode_b_write_type(BWriteType self, SseSerializer serializer);

  @protected
  void sse_encode_blue_event(BlueEvent self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_b_characteristic(
      BCharacteristic self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_device_peripheral_id(
      DevicePeripheralId self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_device_peripheral_id(
      DevicePeripheralId self, SseSerializer serializer);

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void
      sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
          List<BlueAdapter> self, SseSerializer serializer);

  @protected
  void sse_encode_list_Uuid(List<UuidValue> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_u_16_list_prim_u_8_strict(
      List<(int, Uint8List)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_uuid_list_prim_u_8_strict(
      List<(UuidValue, Uint8List)> self, SseSerializer serializer);

  @protected
  void sse_encode_log_entry(LogEntry self, SseSerializer serializer);

  @protected
  void sse_encode_my_mobile_logger(
      MyMobileLogger self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_record_u_16_list_prim_u_8_strict(
      (int, Uint8List) self, SseSerializer serializer);

  @protected
  void sse_encode_record_uuid_list_prim_u_8_strict(
      (UuidValue, Uint8List) self, SseSerializer serializer);

  @protected
  void sse_encode_send_to_dart_logger(
      SendToDartLogger self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
    'store_dart_post_cobject',
  );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__blue__BPeripheral_connect(int port_, int that) {
    return _wire__crate__api__blue__BPeripheral_connect(port_, that);
  }

  late final _wire__crate__api__blue__BPeripheral_connectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
    'frbgen_blue_super_wire__crate__api__blue__BPeripheral_connect',
  );
  late final _wire__crate__api__blue__BPeripheral_connect =
      _wire__crate__api__blue__BPeripheral_connectPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__blue__BPeripheral_disconnect(int port_, int that) {
    return _wire__crate__api__blue__BPeripheral_disconnect(port_, that);
  }

  late final _wire__crate__api__blue__BPeripheral_disconnectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
    'frbgen_blue_super_wire__crate__api__blue__BPeripheral_disconnect',
  );
  late final _wire__crate__api__blue__BPeripheral_disconnect =
      _wire__crate__api__blue__BPeripheral_disconnectPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__blue__BPeripheral_write(
    int port_,
    int that,
    ffi.Pointer<wire_cst_b_characteristic> characteristic,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> data,
    int write_type,
  ) {
    return _wire__crate__api__blue__BPeripheral_write(
      port_,
      that,
      characteristic,
      data,
      write_type,
    );
  }

  late final _wire__crate__api__blue__BPeripheral_writePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_b_characteristic>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Int32,
          )>>('frbgen_blue_super_wire__crate__api__blue__BPeripheral_write');
  late final _wire__crate__api__blue__BPeripheral_write =
      _wire__crate__api__blue__BPeripheral_writePtr.asFunction<
          void Function(
            int,
            int,
            ffi.Pointer<wire_cst_b_characteristic>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            int,
          )>();

  void wire__crate__api__blue__BlueAdapter_listen(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> data,
  ) {
    return _wire__crate__api__blue__BlueAdapter_listen(port_, that, data);
  }

  late final _wire__crate__api__blue__BlueAdapter_listenPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_blue_super_wire__crate__api__blue__BlueAdapter_listen');
  late final _wire__crate__api__blue__BlueAdapter_listen =
      _wire__crate__api__blue__BlueAdapter_listenPtr.asFunction<
          void Function(
              int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__blue__BlueAdapter_stop(int port_, int that) {
    return _wire__crate__api__blue__BlueAdapter_stop(port_, that);
  }

  late final _wire__crate__api__blue__BlueAdapter_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
    'frbgen_blue_super_wire__crate__api__blue__BlueAdapter_stop',
  );
  late final _wire__crate__api__blue__BlueAdapter_stop =
      _wire__crate__api__blue__BlueAdapter_stopPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__blue__adapters(int port_) {
    return _wire__crate__api__blue__adapters(port_);
  }

  late final _wire__crate__api__blue__adaptersPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_blue_super_wire__crate__api__blue__adapters',
  );
  late final _wire__crate__api__blue__adapters =
      _wire__crate__api__blue__adaptersPtr.asFunction<void Function(int)>();

  void wire__crate__api__log__create_log_stream(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> s,
  ) {
    return _wire__crate__api__log__create_log_stream(port_, s);
  }

  late final _wire__crate__api__log__create_log_streamPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_blue_super_wire__crate__api__log__create_log_stream');
  late final _wire__crate__api__log__create_log_stream =
      _wire__crate__api__log__create_log_streamPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__blue__default_adapter(int port_) {
    return _wire__crate__api__blue__default_adapter(port_);
  }

  late final _wire__crate__api__blue__default_adapterPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_blue_super_wire__crate__api__blue__default_adapter',
  );
  late final _wire__crate__api__blue__default_adapter =
      _wire__crate__api__blue__default_adapterPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__blue__device_peripheral_id_infos_to_string(
    int port_,
    ffi.Pointer<wire_cst_device_peripheral_id> that,
  ) {
    return _wire__crate__api__blue__device_peripheral_id_infos_to_string(
      port_,
      that,
    );
  }

  late final _wire__crate__api__blue__device_peripheral_id_infos_to_stringPtr =
      _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                ffi.Int64,
                ffi.Pointer<wire_cst_device_peripheral_id>,
              )>>(
    'frbgen_blue_super_wire__crate__api__blue__device_peripheral_id_infos_to_string',
  );
  late final _wire__crate__api__blue__device_peripheral_id_infos_to_string =
      _wire__crate__api__blue__device_peripheral_id_infos_to_stringPtr
          .asFunction<
              void Function(int, ffi.Pointer<wire_cst_device_peripheral_id>)>();

  void wire__crate__api__log__init_logger(int port_) {
    return _wire__crate__api__log__init_logger(port_);
  }

  late final _wire__crate__api__log__init_loggerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_blue_super_wire__crate__api__log__init_logger',
  );
  late final _wire__crate__api__log__init_logger =
      _wire__crate__api__log__init_loggerPtr.asFunction<void Function(int)>();

  void wire__crate__api__log__my_mobile_logger_new(int port_) {
    return _wire__crate__api__log__my_mobile_logger_new(port_);
  }

  late final _wire__crate__api__log__my_mobile_logger_newPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_blue_super_wire__crate__api__log__my_mobile_logger_new',
  );
  late final _wire__crate__api__log__my_mobile_logger_new =
      _wire__crate__api__log__my_mobile_logger_newPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__log__rust_set_up(int port_) {
    return _wire__crate__api__log__rust_set_up(port_);
  }

  late final _wire__crate__api__log__rust_set_upPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_blue_super_wire__crate__api__log__rust_set_up',
  );
  late final _wire__crate__api__log__rust_set_up =
      _wire__crate__api__log__rust_set_upPtr.asFunction<void Function(int)>();

  void wire__crate__api__log__send_to_dart_logger_new(int port_) {
    return _wire__crate__api__log__send_to_dart_logger_new(port_);
  }

  late final _wire__crate__api__log__send_to_dart_logger_newPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_blue_super_wire__crate__api__log__send_to_dart_logger_new',
  );
  late final _wire__crate__api__log__send_to_dart_logger_new =
      _wire__crate__api__log__send_to_dart_logger_newPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__log__send_to_dart_logger_set_stream_sink(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> stream_sink,
  ) {
    return _wire__crate__api__log__send_to_dart_logger_set_stream_sink(
      port_,
      stream_sink,
    );
  }

  late final _wire__crate__api__log__send_to_dart_logger_set_stream_sinkPtr =
      _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                ffi.Int64,
                ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              )>>(
    'frbgen_blue_super_wire__crate__api__log__send_to_dart_logger_set_stream_sink',
  );
  late final _wire__crate__api__log__send_to_dart_logger_set_stream_sink =
      _wire__crate__api__log__send_to_dart_logger_set_stream_sinkPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheralPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
    'frbgen_blue_super_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral',
  );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheralPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheralPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
    'frbgen_blue_super_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral',
  );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheral =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBPeripheralPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapterPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
    'frbgen_blue_super_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter',
  );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapterPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapterPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
    'frbgen_blue_super_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter',
  );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapterPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<wire_cst_b_characteristic>
      cst_new_box_autoadd_b_characteristic() {
    return _cst_new_box_autoadd_b_characteristic();
  }

  late final _cst_new_box_autoadd_b_characteristicPtr = _lookup<
          ffi
          .NativeFunction<ffi.Pointer<wire_cst_b_characteristic> Function()>>(
      'frbgen_blue_super_cst_new_box_autoadd_b_characteristic');
  late final _cst_new_box_autoadd_b_characteristic =
      _cst_new_box_autoadd_b_characteristicPtr
          .asFunction<ffi.Pointer<wire_cst_b_characteristic> Function()>();

  ffi.Pointer<wire_cst_device_peripheral_id>
      cst_new_box_autoadd_device_peripheral_id() {
    return _cst_new_box_autoadd_device_peripheral_id();
  }

  late final _cst_new_box_autoadd_device_peripheral_idPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<wire_cst_device_peripheral_id> Function()>>(
      'frbgen_blue_super_cst_new_box_autoadd_device_peripheral_id');
  late final _cst_new_box_autoadd_device_peripheral_id =
      _cst_new_box_autoadd_device_peripheral_idPtr
          .asFunction<ffi.Pointer<wire_cst_device_peripheral_id> Function()>();

  ffi.Pointer<ffi.Int16> cst_new_box_autoadd_i_16(int value) {
    return _cst_new_box_autoadd_i_16(value);
  }

  late final _cst_new_box_autoadd_i_16Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int16> Function(ffi.Int16)>>(
    'frbgen_blue_super_cst_new_box_autoadd_i_16',
  );
  late final _cst_new_box_autoadd_i_16 = _cst_new_box_autoadd_i_16Ptr
      .asFunction<ffi.Pointer<ffi.Int16> Function(int)>();

  ffi.Pointer<
          wire_cst_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter>
      cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
    int len,
  ) {
    return _cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter(
      len,
    );
  }

  late final _cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapterPtr =
      _lookup<
          ffi.NativeFunction<
              ffi.Pointer<
                      wire_cst_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter>
                  Function(ffi.Int32)>>(
    'frbgen_blue_super_cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter',
  );
  late final _cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter =
      _cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapterPtr
          .asFunction<
              ffi.Pointer<
                      wire_cst_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter>
                  Function(int)>();

  ffi.Pointer<wire_cst_list_Uuid> cst_new_list_Uuid(int len) {
    return _cst_new_list_Uuid(len);
  }

  late final _cst_new_list_UuidPtr = _lookup<
          ffi
          .NativeFunction<ffi.Pointer<wire_cst_list_Uuid> Function(ffi.Int32)>>(
      'frbgen_blue_super_cst_new_list_Uuid');
  late final _cst_new_list_Uuid = _cst_new_list_UuidPtr
      .asFunction<ffi.Pointer<wire_cst_list_Uuid> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_new_list_prim_u_8_loose(
    int len,
  ) {
    return _cst_new_list_prim_u_8_loose(len);
  }

  late final _cst_new_list_prim_u_8_loosePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(
              ffi.Int32)>>('frbgen_blue_super_cst_new_list_prim_u_8_loose');
  late final _cst_new_list_prim_u_8_loose = _cst_new_list_prim_u_8_loosePtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(
              ffi.Int32)>>('frbgen_blue_super_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  ffi.Pointer<wire_cst_list_record_u_16_list_prim_u_8_strict>
      cst_new_list_record_u_16_list_prim_u_8_strict(int len) {
    return _cst_new_list_record_u_16_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_record_u_16_list_prim_u_8_strictPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_record_u_16_list_prim_u_8_strict> Function(
            ffi.Int32,
          )>>('frbgen_blue_super_cst_new_list_record_u_16_list_prim_u_8_strict');
  late final _cst_new_list_record_u_16_list_prim_u_8_strict =
      _cst_new_list_record_u_16_list_prim_u_8_strictPtr.asFunction<
          ffi.Pointer<wire_cst_list_record_u_16_list_prim_u_8_strict> Function(
              int)>();

  ffi.Pointer<wire_cst_list_record_uuid_list_prim_u_8_strict>
      cst_new_list_record_uuid_list_prim_u_8_strict(int len) {
    return _cst_new_list_record_uuid_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_record_uuid_list_prim_u_8_strictPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_record_uuid_list_prim_u_8_strict> Function(
            ffi.Int32,
          )>>('frbgen_blue_super_cst_new_list_record_uuid_list_prim_u_8_strict');
  late final _cst_new_list_record_uuid_list_prim_u_8_strict =
      _cst_new_list_record_uuid_list_prim_u_8_strictPtr.asFunction<
          ffi.Pointer<wire_cst_list_record_uuid_list_prim_u_8_strict> Function(
              int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
    'dummy_method_to_enforce_bundling',
  );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message)>>;
typedef DartPort = ffi.Int64;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_b_characteristic extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> uuid;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> service_uuid;
}

final class wire_cst_list_prim_u_8_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_record_u_16_list_prim_u_8_strict extends ffi.Struct {
  @ffi.Uint16()
  external int field0;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> field1;
}

final class wire_cst_list_record_u_16_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<wire_cst_record_u_16_list_prim_u_8_strict> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_record_uuid_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> field0;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> field1;
}

final class wire_cst_list_record_uuid_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<wire_cst_record_uuid_list_prim_u_8_strict> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_Uuid extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_device_peripheral_id extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  @ffi.Bool()
  external bool is_connected;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> address;

  external ffi.Pointer<ffi.Int16> tx_power_level;

  external ffi.Pointer<ffi.Int16> rssi;

  external ffi.Pointer<wire_cst_list_record_u_16_list_prim_u_8_strict>
      manufacturer_data;

  external ffi.Pointer<wire_cst_list_record_uuid_list_prim_u_8_strict>
      service_data;

  external ffi.Pointer<wire_cst_list_Uuid> services;

  @ffi.UintPtr()
  external int peripheral;
}

final class wire_cst_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlueAdapter
    extends ffi.Struct {
  external ffi.Pointer<ffi.UintPtr> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_BlueEvent_DeviceDiscovered extends ffi.Struct {
  external ffi.Pointer<wire_cst_device_peripheral_id> field0;
}

final class wire_cst_BlueEvent_DeviceUpdated extends ffi.Struct {
  external ffi.Pointer<wire_cst_device_peripheral_id> field0;
}

final class wire_cst_BlueEvent_DeviceConnected extends ffi.Struct {
  external ffi.Pointer<wire_cst_device_peripheral_id> field0;
}

final class wire_cst_BlueEvent_DeviceDisconnected extends ffi.Struct {
  external ffi.Pointer<wire_cst_device_peripheral_id> field0;
}

final class wire_cst_BlueEvent_ManufacturerDataAdvertisement
    extends ffi.Struct {
  external ffi.Pointer<wire_cst_device_peripheral_id> field0;

  external ffi.Pointer<wire_cst_list_record_u_16_list_prim_u_8_strict> field1;
}

final class wire_cst_BlueEvent_ServiceDataAdvertisement extends ffi.Struct {
  external ffi.Pointer<wire_cst_device_peripheral_id> field0;

  external ffi.Pointer<wire_cst_list_record_uuid_list_prim_u_8_strict> field1;
}

final class wire_cst_BlueEvent_ServicesAdvertisement extends ffi.Struct {
  external ffi.Pointer<wire_cst_device_peripheral_id> field0;

  external ffi.Pointer<wire_cst_list_Uuid> field1;
}

final class wire_cst_BlueEvent_StateUpdate extends ffi.Struct {
  @ffi.Int32()
  external int field0;
}

final class wire_cst_BlueEvent_ERROR extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> field0;
}

final class BlueEventKind extends ffi.Union {
  external wire_cst_BlueEvent_DeviceDiscovered DeviceDiscovered;

  external wire_cst_BlueEvent_DeviceUpdated DeviceUpdated;

  external wire_cst_BlueEvent_DeviceConnected DeviceConnected;

  external wire_cst_BlueEvent_DeviceDisconnected DeviceDisconnected;

  external wire_cst_BlueEvent_ManufacturerDataAdvertisement
      ManufacturerDataAdvertisement;

  external wire_cst_BlueEvent_ServiceDataAdvertisement ServiceDataAdvertisement;

  external wire_cst_BlueEvent_ServicesAdvertisement ServicesAdvertisement;

  external wire_cst_BlueEvent_StateUpdate StateUpdate;

  external wire_cst_BlueEvent_ERROR ERROR;
}

final class wire_cst_blue_event extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external BlueEventKind kind;
}

final class wire_cst_log_entry extends ffi.Struct {
  @ffi.Int64()
  external int time_millis;

  @ffi.Int32()
  external int level;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> tag;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> msg;
}

final class wire_cst_my_mobile_logger extends ffi.Opaque {}

final class wire_cst_send_to_dart_logger extends ffi.Opaque {}
